export const AUTH_START ='AUTH_START'  // LOG IN A USER
export const AUTH_SUCCESS ='AUTH_SUCCESS' // CREATE A USER
export const AUTH_FAIL ='AUTH_FAIL' // FAILURE WHEN LOGGING IN A USER
export const AUTH_LOGOUT ='AUTH_LOGOUT' // LOGOUT