# Generated by Django 3.0.3 on 2020-07-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='xkdjvkdjvk ckvjkdfgvjkfv lcknbclnblcnklc   ncklnblckfnvlkdf  cv;bnfllfv cv;nfvncfv', max_length=500),
            preserve_default=False,
        ),
    ]
